version: '3.3'
services:
    mongo:
        ports:
            - '${EXTERNAL_PORT}:27017'
        container_name: ${MONGO_HOST}
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
        image: mongo
        env_file:
            - .env

    telegram_bot:
        build:
            context: ./
            dockerfile: telegram_bot.Dockerfile
        container_name: telegram_bot
        restart: always
        depends_on:
            - mongo

    island_parser:
        build:
            context: ./
            dockerfile: island_parser.Dockerfile
        container_name: island_parser
        restart: always
        depends_on:
            - mongo

